spring.application.name=notes
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb://medilabo:medilabo123@mongodb:27017/notes_db?authSource=admin
spring.data.mongodb.database=notes_db

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
