spring.application.name=demographics
server.port=8081

# Database configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/demographics_db
spring.datasource.username=medilabo
spring.datasource.password=medilabo123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
